---
- name: Install nginx
  apt: name=nginx state=present

- name: Copy nginx configuration for wordpress
  template: src=default.conf dest=/etc/nginx/sites-enabled/default.conf
  notify: restart nginx

- name: insert ufw rule for nginx
  ufw:
    rule: allow
    port: "{{ nginx_port }}"
    proto: tcp

- name: http service state
  service: name=nginx state=started enabled=yes
