---
- name: Install WordPress, Nginx, and PHP-FPM
  hosts: tag_Name_Web_Server_1 
  remote_user: centos
  # remote_user: user
  become: yes
  become_method: sudo
  roles:
    - common
    - nginx
    - php-fpm
    - wordpress

- name: Install MySQL
  hosts: tag_Name_DB_Server_1
  remote_user: centos
  # remote_user: user
  become: yes
  become_method: sudo
  roles:
    - common
    - mysql
