---
- name: Install WordPress, MariaDB, Nginx, and PHP-FPM
  hosts: tag_Name_Web_Server_1
  remote_user: ubuntu
  become: yes

  roles:
    - common
    - mariadb
    - nginx
    - php-fpm
    - wordpress
